import { PlantType, ZombieType } from './types';
import type { PlantConfig, ZombieConfig } from './types';

export const PLANT_CONFIGS: Record<PlantType, PlantConfig> = {
  [PlantType.sunflower]: {
    type: PlantType.sunflower,
    hp: 100,
    cost: 50,
    cooldown: 7500,
    damage: 0,
    special: { producesSun: true, sunValue: 25 },
  },
  [PlantType.peashooter]: {
    type: PlantType.peashooter,
    hp: 100,
    cost: 100,
    cooldown: 1500,
    damage: 20,
    special: {},
  },
  [PlantType.wallnut]: {
    type: PlantType.wallnut,
    hp: 400,
    cost: 50,
    cooldown: 0,
    damage: 0,
    special: {},
  },
  [PlantType.snowpea]: {
    type: PlantType.snowpea,
    hp: 100,
    cost: 175,
    cooldown: 1500,
    damage: 20,
    special: { slows: true, slowFactor: 0.5 },
  },
  [PlantType.cherrybomb]: {
    type: PlantType.cherrybomb,
    hp: 1,
    cost: 150,
    cooldown: 0,
    damage: 1800,
    special: { instant: true, aoe: true, aoeRange: 1 },
  },
  [PlantType.potatomine]: {
    type: PlantType.potatomine,
    hp: 100,
    cost: 25,
    cooldown: 0,
    damage: 1800,
    special: { armTime: 15000 },
  },
  [PlantType.repeater]: {
    type: PlantType.repeater,
    hp: 100,
    cost: 200,
    cooldown: 1500,
    damage: 20,
    special: { shots: 2 },
  },
  [PlantType.chomper]: {
    type: PlantType.chomper,
    hp: 100,
    cost: 150,
    cooldown: 0,
    damage: 1800,
    special: { digestTime: 30000 },
  },
  [PlantType.tallnut]: {
    type: PlantType.tallnut,
    hp: 800,
    cost: 125,
    cooldown: 0,
    damage: 0,
    special: { blocksVaulters: true },
  },
  [PlantType.torchwood]: {
    type: PlantType.torchwood,
    hp: 100,
    cost: 175,
    cooldown: 0,
    damage: 0,
    special: { fireDamageMultiplier: 2 },
  },
};

export const ZOMBIE_CONFIGS: Record<ZombieType, ZombieConfig> = {
  [ZombieType.regular]: {
    type: ZombieType.regular,
    hp: 100,
    speed: 0.3,
    damage: 100,
    special: {},
  },
  [ZombieType.conehead]: {
    type: ZombieType.conehead,
    hp: 200,
    speed: 0.3,
    damage: 100,
    special: {},
  },
  [ZombieType.buckethead]: {
    type: ZombieType.buckethead,
    hp: 400,
    speed: 0.3,
    damage: 100,
    special: {},
  },
  [ZombieType.flag]: {
    type: ZombieType.flag,
    hp: 100,
    speed: 0.45,
    damage: 100,
    special: {},
  },
  [ZombieType.polevaulting]: {
    type: ZombieType.polevaulting,
    hp: 200,
    speed: 0.6,
    damage: 100,
    special: { jumps: true },
  },
  [ZombieType.newspaper]: {
    type: ZombieType.newspaper,
    hp: 150,
    speed: 0.2,
    damage: 100,
    special: { enrageSpeed: 0.8, enrageThreshold: 0.5 },
  },
  [ZombieType.football]: {
    type: ZombieType.football,
    hp: 500,
    speed: 0.55,
    damage: 100,
    special: {},
  },
  [ZombieType.gargantuar]: {
    type: ZombieType.gargantuar,
    hp: 1500,
    speed: 0.15,
    damage: 300,
    special: { throwsImp: true, impThrown: false },
  },
};
